/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactSystem;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
/**
 *
 * @author HUDA
 */
public class BirthDay extends javax.swing.JFrame {

    /**
     * Creates new form BirthDay
     */
    public BirthDay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uBirthDay = new javax.swing.JButton();
        rBirthDay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        uBirthDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uBirthDay.setText("View Upcomming BirthDays");
        uBirthDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBirthDayActionPerformed(evt);
            }
        });
        jPanel1.add(uBirthDay);
        uBirthDay.setBounds(30, 120, 330, 31);

        rBirthDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rBirthDay.setText("View Recent BirthDays");
        rBirthDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBirthDayActionPerformed(evt);
            }
        });
        jPanel1.add(rBirthDay);
        rBirthDay.setBounds(30, 70, 330, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Downloads\\contact.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBirthDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBirthDayActionPerformed
        // TODO add your handling code here:
        RecentBirthDay d=new RecentBirthDay();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_rBirthDayActionPerformed

    private void uBirthDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBirthDayActionPerformed
        try {
            // TODO add your handling code here:
            UpcommingBirthday b=new UpcommingBirthday();
            this.setVisible(false);
            b.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BirthDay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uBirthDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BirthDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rBirthDay;
    private javax.swing.JButton uBirthDay;
    // End of variables declaration//GEN-END:variables
}
