/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactSystem;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
/**
 *
 * @author HUDA
 */
public class RecentBirthDay extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form RecentBirthDay
     */
    public RecentBirthDay() {
        initComponents();
        this.getConnection();
        this.findBirthDay();
               
 
    }

        void getConnection()
{
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/contact?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
        System.out.println("Connection established");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(AdditionalInformation.class.getName()).log(Level.SEVERE, null, ex);
    }
}
        void addRowToTable(String name,String lastname,long d,String s)
        {
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.addRow(new Object[]{name,lastname,d,s});
            
        }
        void findBirthDay()
        {
            
                
    try {
        Calendar cal=Calendar.getInstance();
        int month=cal.get(Calendar.MONTH)+1;
        Statement smt;
        ResultSet rs;
        String name,lastname;
        String s=null;
        String query="select day(dob),FirstName,LastName from information where month(dob)='"+month+"'";
        smt=con.createStatement();
        rs=smt.executeQuery(query);
        while(rs.next())
        {
           name=rs.getString("FirstName");
           lastname=rs.getString("Lastname");
           long d=rs.getLong("day(dob)");
           long dat=cal.get(Calendar.DAY_OF_MONTH);
                      if(d<=dat)
                      {
                          dat=dat-d;
                          System.out.println(dat-d);
                             if(dat==0)
                             {
                                 s="Today!!";
                             }  
                             if(dat==1)
                             {
                                 s="Yesterday";
                             }
                             if(dat>1)
                             {
                                 s="days passed";
                             }
                          addRowToTable(name,lastname,dat,s);
                      }
                      
                      
           

           
        }
    } catch (SQLException ex) {
        Logger.getLogger(RecentBirthDay.class.getName()).log(Level.SEVERE, null, ex);
    }
                
               
                
                
        }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "LastName", "Date", "Days Ago"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 340, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Downloads\\contact.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecentBirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecentBirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecentBirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecentBirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecentBirthDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
