/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactSystem;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HUDA
 */
public class Recent extends javax.swing.JFrame {
Connection con;
ResultSet rs;
java.sql.Time t;
java.sql.Timestamp s;
    /**
     * Creates new form Recent
     */
    public Recent() {
        initComponents();
        getConnection();
        getResult();
    }
void getConnection()
{
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/contact?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Recent.class.getName()).log(Level.SEVERE, null, ex);
    }
   

}
void addRowToTable(String fname,String lname,String contact,Date d,Time t)
{
    DefaultTableModel model=(DefaultTableModel)table.getModel();
    model.addRow(new Object[]{fname,lname,contact,t,d});
    
    
}
void getResult()
   {
    try {
        Statement sm;
        String query="select firstname,lastname,contact_no,calldate,calltime from information natural join recent";
        sm=con.createStatement();
        rs=sm.executeQuery(query);
        while(rs.next())
        {
            String fname=rs.getString("firstname");
            String lname=rs.getString("lastname");
            String contact=rs.getString("contact_no");
            Date d=rs.getDate("calldate");
             t=rs.getTime("calltime");
           addRowToTable(fname,lname,contact,d,t);
        }
    } catch (SQLException ex) {
        Logger.getLogger(Recent.class.getName()).log(Level.SEVERE, null, ex);
    }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName", "ContactNo", "CallTime", "CallDate"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 450, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Documents\\NetBeansProjects\\JavaApplication\\src\\contactSystem\\contact.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void removeRow()
{
    DefaultTableModel model=(DefaultTableModel)table.getModel();
    model.removeRow(table.getSelectedRow());
    
   }
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
    try {
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        String contact=table.getModel().getValueAt(index,2).toString();
        String time=table.getModel().getValueAt(index,3).toString();
        t=Time.valueOf(time);
        System.out.println(t);
        Statement sm;
        sm=con.createStatement();
        
        
        String query="delete from recent where contact_no='"+contact+"' and calltime='"+t+"'";
        JOptionPane.showMessageDialog(rootPane,"Deleted Sucessfully");
         removeRow();

        sm.executeUpdate(query);
        
    } catch (SQLException ex) {
        Logger.getLogger(Recent.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
       
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
