/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactSystem;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUDA
 */
public class UpcommingBirthday extends javax.swing.JFrame {
 Connection con;
    /**
     * Creates new form UpcommingBirthday
     */
    public UpcommingBirthday() throws SQLException {
        initComponents();
         this.getConnection();
        this.findBirthDay();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName", "Day to go!"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 270, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contactSystem/contact.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    void getConnection()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/contact?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpcommingBirthday.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void addRowToTable(String name,String lastname,long d,String s)
        {
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.addRow(new Object[]{name,lastname,d,s});
            
        }
    void findBirthDay() throws SQLException
    {
        Statement smt;
        ResultSet rs;
        String name,lastname,s = null;
        Calendar cal=Calendar.getInstance();
        int month=cal.get(Calendar.MONTH)+1;
        String query="select day(dob),FirstName,LastName from information where month(dob)='"+month+"'";
        smt=con.createStatement();
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            try {
                name=rs.getString("FirstName");
                lastname=rs.getString("Lastname");
                long d=rs.getLong("day(dob)");
                long dat=cal.get(Calendar.DAY_OF_MONTH);
                
                
                if(d>=dat)
                {
                    d=d-dat;
                    System.out.println(d-dat);
                    if(d==0)
                    {
                        s="Today!!";
                    }
                    if(d==1)
                    {
                        s="Tommorrow!!";
                    }
                    if(d>1)
                    {
                        s="days passed";
                    }
                    addRowToTable(name,lastname,d,s);
                }
            } catch (SQLException ex) {
                Logger.getLogger(UpcommingBirthday.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpcommingBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpcommingBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpcommingBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpcommingBirthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UpcommingBirthday().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UpcommingBirthday.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
