/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactSystem;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HUDA
 */
public class ViewContact extends javax.swing.JFrame {
Connection con;
ResultSet rs;
AdditionalInformation m=new AdditionalInformation();
    /**
     * Creates new form ViewContact
     */
    public ViewContact() {
    try {
        String name;
        initComponents();
           String number;    

        this.getConnection();
        Statement sm;
        sm=con.createStatement();
        String query="select FirstName,contact_no from information order by FirstName";
        rs=sm.executeQuery(query);
         DefaultTableModel model=(DefaultTableModel)contacts.getModel();
        while(rs.next())
        {
           name=rs.getString("FirstName");
           number=rs.getString("contact_no");
           model.addRow(new Object[]{name,number});
        }
        
        
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(ViewContact.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
private void getConnection() throws ClassNotFoundException, SQLException
{
        Class.forName("com.mysql.cj.jdbc.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/contact?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contacts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        contacts.setBackground(new java.awt.Color(0, 0, 0));
        contacts.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        contacts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contacts.setForeground(new java.awt.Color(255, 255, 255));
        contacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone No"
            }
        ));
        contacts.setGridColor(new java.awt.Color(102, 204, 0));
        contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactsMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(contacts);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 530, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Downloads\\contact.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseClicked
    try {
        String lname = null,contact = null;
        java.util.Date dob = null;
        int index=contacts.getSelectedRow();
        String name=contacts.getModel().getValueAt(index,0).toString();
        String contacts1=contacts.getModel().getValueAt(index,1).toString();
        Statement sm;
        sm=con.createStatement();
        String query="select Lastname,contact_no,dob from information where Firstname='"+name+"' and contact_no='"+contacts1+"'";
        rs=sm.executeQuery(query);
        while(rs.next())
        {
           
        lname=rs.getString("Lastname");
        contact=rs.getString("contact_no");
        
        dob=rs.getDate("dob");
        }
m.setFName(name);
       m.setLastName(lname);
       m.setContact(contact);
       m.setDate(dob);
       m.setVisible(true);
      
       
    } catch (SQLException ex) {
        Logger.getLogger(ViewContact.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_contactsMouseClicked

    private void contactsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseExited
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_contactsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contacts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
