/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HUDA
 */
public class DLItem extends javax.swing.JFrame {
Connection con;
Statement smt;
ResultSet rs;
Email e=new Email();
String i="i0";
String itemName;
    /**
     * Creates new form DLItem
     */
    public DLItem() {
        initComponents();
        getConnection();
        data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Oid", "Odate", "Quantity", "Amount", "ItemId"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 370, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectPackage/stationary.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int x=table.getSelectedRow();
         itemName=model.getValueAt(x,4).toString();
        e.setItemName(itemName);
        int quantity=Integer.parseInt(model.getValueAt(x,2).toString());
        e.getQuantity(quantity);
        int amount=Integer.parseInt(model.getValueAt(x,3).toString());
        e.setAdvance(amount);
        String date=model.getValueAt(x,1).toString();
        e.getDate(date);
        setMail();
        setSubject2();
        e.delayedArea();
        e.setVisible(true);
        
        
    }//GEN-LAST:event_tableMouseClicked
   private void getConnection()
    {
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
   
   private void data()
   {
       DefaultTableModel model=(DefaultTableModel)table.getModel();
    try {
        smt=con.createStatement();
        String query="select oid,orders.ItemId,odate,orders.quantity,amount,ItemName from orders join items on orders.ItemId=items.ItemId;";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            String id=rs.getString("oid");
            java.sql.Date d=rs.getDate("odate");
            int quantity=rs.getInt("quantity");
            int amount=rs.getInt("amount");
            String Itemid=rs.getString("ItemName");
            i=rs.getString("ItemId");
           model.addRow(new Object[]{id,d,quantity,amount,Itemid});
            
            
                    
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(DLItem.class.getName()).log(Level.SEVERE, null, ex);
    }
   }
   public String getEmail()
{
    String mail="";
    try {
        smt=con.createStatement();
        String query="select email from items natural join supplier where itemid='"+i+"'";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            mail=rs.getString("email");
            
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(ListItems.class.getName()).log(Level.SEVERE, null, ex);
    }
    return mail;
}
public void setMail()
{
    String mail=getEmail();
  

    e.extractEmail(mail);
    
    
}
private void setSubject2()
{
   
        String s="Complaint for order "+itemName+" not received";
        
        e.setSubject(s);
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DLItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
