/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;
import javax.mail.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author HUDA
 */
public class Email extends javax.swing.JFrame {
String name="";
int quan=0;
int adv=0;
String s;
    /**
     * Creates new form Email
     */
    public Email() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fromEmail = new javax.swing.JTextField();
        subjectEmail = new javax.swing.JTextField();
        toEmail = new javax.swing.JTextField();
        emailBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        emailBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Email System\n");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 10, 160, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Text");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 230, 70, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 70, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("From");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 70, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Subject");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 180, 70, 30);

        fromEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromEmail.setText("choicestationary6@gmail.com");
        fromEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromEmailActionPerformed(evt);
            }
        });
        jPanel1.add(fromEmail);
        fromEmail.setBounds(150, 130, 380, 30);

        subjectEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subjectEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectEmailActionPerformed(evt);
            }
        });
        jPanel1.add(subjectEmail);
        subjectEmail.setBounds(120, 180, 640, 30);

        toEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        toEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toEmailActionPerformed(evt);
            }
        });
        jPanel1.add(toEmail);
        toEmail.setBounds(150, 80, 380, 30);

        emailBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailBtn.setText("Send");
        emailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtnActionPerformed(evt);
            }
        });
        jPanel1.add(emailBtn);
        emailBtn.setBounds(0, 360, 110, 30);

        messageArea.setColumns(20);
        messageArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 230, 640, 280);

        emailBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailBtn1.setText("Logout");
        emailBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(emailBtn1);
        emailBtn1.setBounds(0, 310, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void extractEmail(String mail)
{
    
    toEmail.setText(mail);
}
public void getEmailType(String m)
{
    if(m.equals("order"))
    {
        this.setTextArea();
    }
    
}
public void defectiveArea(String m)
{
    messageArea.append("I had placed order of ");
    messageArea.append(m+" on [date] worth [bill amount]");
    messageArea.append("\nThe product received were damaged.");
    messageArea.append("I had kept the goods in same form as received.The same can be chechked by your");
    messageArea.append("while picking the order");
    messageArea.append("\nHence i would request you to kindly attend to my complaint urgently and provide me with replaced good at earliest");
    messageArea.append("\nPlease not my order detail for your reference");
    messageArea.append("\nDate of order-[order date]");
    messageArea.append("\nName:Huda Shaikh");
    messageArea.append("\nItem name-"+m);
    messageArea.append("\nQuantity-[quantity]");
    messageArea.append("\nTotal price:[price]");
    messageArea.append("Thanking you in anticipation that my complaint will be resolved");
    
    
}
public void delayedArea()
{
    messageArea.append("With due respect, this letter has been written to inform you \nthat I have placed an order of "+quan+" packs of ");
    messageArea.append(name+" on "+s+"\nI have also paid the amount "+adv+ "through cheque ad advance but still.\n I have got no response from your end");
    messageArea.append("\n I have called several times on your company’s number but I have got no response.\n What kind of service are you providing to the customers? \nI am waiting for my goods for the last [duration].\n This sort of unprofessional behavior can result in losing your customers.\n Please respond to my request to refund me the amount or sent the good at early as possible \n I hope you will take action to my complaint as soon as possible. \nThank you.");
}

public void setSubject(String subject)
{
    subjectEmail.setText(subject);
}
     private void setTextArea()
     {
         
        messageArea.append("As per our discussion");
        messageArea.append("\nI am writing to order "+quan+" packs of "+name+" from your buisness");
        messageArea.append("\nI intend to pay by cheque,I have enclosed a advance of "+adv);
        messageArea.append("\nIf possible I would like to have the items delivered by [possible delivery date].");
        messageArea.append("""
                           
        Should any concerns arise, please contact me by phone or email. 
        You may email me at choicestationary6@gmail.com or by calling me at 644-566-2299.
        I'd also like to thank you on behalf of choice stationary
        We appreciate your services and look forward to your continued partnership""");
        
        
        
        
     }
     public void getDate(String d)
     {
       s=d;  
     }
     public void getQuantity(int quantity)
     {
         quan=quantity;
     }
     public void setItemName(String iname)
     {
        name=iname; 
     }
     public void setAdvance(int advance)
     {
    adv = advance;
     }
     
    private void fromEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromEmailActionPerformed

    private void subjectEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectEmailActionPerformed

    private void toEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toEmailActionPerformed

    private void emailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtnActionPerformed
        // TODO add your handling code here:
        String toMail=toEmail.getText();
        String fromMail=fromEmail.getText();
        String password="ryylmkmwiwvtpjcu";
        String subject=subjectEmail.getText();
        Properties properties=new Properties();
        properties.put("mail.smtp.auth","true");
           properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        





        properties.put("mail.smtp.port","587");
        
        Session session=Session.getDefaultInstance(properties,new javax.mail.Authenticator()
        {
            @Override
            protected PasswordAuthentication getPasswordAuthentication()
            {
                return new PasswordAuthentication(fromMail,password);
            }
        });
        MimeMessage message=new MimeMessage(session);
        try {
            message.setFrom(new InternetAddress(fromMail));
            message.addRecipient(Message.RecipientType.TO,new InternetAddress(toMail));
            /* Set the specified recipient type to the given addresses.*/
            message.setSubject(subject);
            message.setText(messageArea.getText());
            Transport.send(message);
            /*message sent to receipents specified in meesage */
            
        } catch (MessagingException ex) {
            Logger.getLogger(Email.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"Email sent successfully");
        
        
    }//GEN-LAST:event_emailBtnActionPerformed

    private void emailBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainPage p=new MainPage();
        p.setVisible(true);
    }//GEN-LAST:event_emailBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emailBtn;
    private javax.swing.JButton emailBtn1;
    private javax.swing.JTextField fromEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextField subjectEmail;
    private javax.swing.JTextField toEmail;
    // End of variables declaration//GEN-END:variables
}
