/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.awt.List;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import java.util.ArrayList;
/**
 *
 * @author HUDA
 */
public class ListItems extends javax.swing.JFrame {
Connection con;
Statement smt;
ResultSet rs;
        ArrayList<String> al=new ArrayList<>();
          Email e=new Email();
    /**
     * Creates new form ListItems
     */
    
    public ListItems() {
        initComponents();
        getConnection();
        getList();
        generateStringArray();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderItem = new javax.swing.JButton();
        lateDelivery = new javax.swing.JButton();
        listField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select ItemId for which you want to send email  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 0, 430, 60);

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 190, 130);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Items having 0 Quantity");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 230, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Select the email type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 80, 160, 30);

        orderItem.setBackground(new java.awt.Color(51, 51, 255));
        orderItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderItem.setForeground(new java.awt.Color(255, 255, 255));
        orderItem.setText("Order Item");
        orderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderItemActionPerformed(evt);
            }
        });
        jPanel1.add(orderItem);
        orderItem.setBounds(220, 120, 130, 30);

        lateDelivery.setBackground(new java.awt.Color(51, 51, 255));
        lateDelivery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lateDelivery.setForeground(new java.awt.Color(255, 255, 255));
        lateDelivery.setText("Late Delivery\n");
        lateDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lateDeliveryActionPerformed(evt);
            }
        });
        jPanel1.add(lateDelivery);
        lateDelivery.setBounds(360, 120, 130, 30);
        jPanel1.add(listField);
        listField.setBounds(130, 120, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ItemId ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 120, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectPackage/stationary.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        String s=(String)list.getSelectedValue();
        listField.setText(s);
        
    }//GEN-LAST:event_listMouseClicked

    private void orderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderItemActionPerformed
        // TODO add your handling code here:
      
        
       
       String m=listField.getText();
       OrderTableEntry o=new OrderTableEntry();
       o.getItemId(m);
       o.setVisible(true);
        
        
       
        
        
        
    }//GEN-LAST:event_orderItemActionPerformed

    private void lateDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateDeliveryActionPerformed
        // TODO add your handling code here:
      DLItem m=new DLItem();
      m.setVisible(true);
    }//GEN-LAST:event_lateDeliveryActionPerformed


    /**
     * @param args the command line arguments
     */
    private void getConnection()
    {
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private void getList()
    {
    try {

        smt=con.createStatement();
        String query="select ItemId from items where Quantity=0";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            al.add(rs.getString("ItemId"));
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(ListItems.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }
    private void generateStringArray()
    {
        int length=al.size();
        String m[]=new String[length];
        for(int i=0;i<length;i++)
        {
            m[i]=al.get(i);
        }
        list.setModel(new DefaultComboBoxModel<>(m));
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lateDelivery;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField listField;
    private javax.swing.JButton orderItem;
    // End of variables declaration//GEN-END:variables
}
