/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import jaco.mp3.player.MP3Player;
import java.io.File;

/**
 *
 * @author HUDA
 */
public class MainPage extends javax.swing.JFrame {
String song="C:\\Users\\HUDA\\Downloads\\windows_xp_startup.mp3";
MP3Player player=new MP3Player(new File(song));
           Voice voice;
VoiceManager vm; 
   String spea="Hello my name is kevin16.I have beem developed in java.Welcome to choice stationary choose any of the below operation to proceed";
     
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.playMusic();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productBtn = new javax.swing.JButton();
        stocksBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        billBtn = new javax.swing.JButton();
        logoutBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome!!!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 0, 110, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Choose the operation");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 40, 300, 40);

        productBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productBtn.setForeground(new java.awt.Color(51, 51, 255));
        productBtn.setText("View Product");
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        jPanel1.add(productBtn);
        productBtn.setBounds(60, 110, 130, 30);

        stocksBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stocksBtn.setForeground(new java.awt.Color(51, 51, 255));
        stocksBtn.setText("View Sales Report");
        stocksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocksBtnActionPerformed(evt);
            }
        });
        jPanel1.add(stocksBtn);
        stocksBtn.setBounds(60, 180, 130, 30);

        supplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplierBtn.setForeground(new java.awt.Color(51, 51, 255));
        supplierBtn.setText("View Supplier");
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(supplierBtn);
        supplierBtn.setBounds(210, 110, 110, 30);

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(51, 51, 255));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(60, 250, 110, 30);

        billBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        billBtn.setForeground(new java.awt.Color(51, 51, 255));
        billBtn.setText("Generate Bill");
        billBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBtnActionPerformed(evt);
            }
        });
        jPanel1.add(billBtn);
        billBtn.setBounds(210, 180, 110, 30);

        logoutBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutBtn1.setForeground(new java.awt.Color(51, 51, 255));
        logoutBtn1.setText("Email Generation");
        logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn1);
        logoutBtn1.setBounds(210, 250, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Desktop\\complete web development\\pictures\\stationary.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void spe(String spea)
{
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
    vm=VoiceManager.getInstance();
        voice=vm.getVoice("kevin16");
         voice.setRate(120);// Setting the rate of the voice
            voice.setPitch(150);// Setting the Pitch of the voice
            voice.setVolume(3);
 
        // Setting the volume of the voice
        voice.allocate();
           

     
        
        voice.speak(spea);
}
private void playMusic()
{
    player.play();
    
        
}
    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
      spea="Now you are going to view product information.Here you can update,insert or delete information";
      spe(spea);
        Product p1=new Product();
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_productBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
 
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void stocksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocksBtnActionPerformed
        // TODO add your handling code here:
        spea="Now you are going to view sales report";
      spe(spea);
        SalesReport s=new SalesReport();
        s.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_stocksBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
 spea="Now you are going to view supplier information.Here you can update,insert or delete information";
 spe(spea);
        Supplier s=new Supplier();
this.setVisible(false);
s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void billBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBtnActionPerformed
        // TODO add your handling code here:
        spea="Now you are going to generate bill for customer.Yuhoo!!";
 spe(spea);
        Bill b= new Bill();
        this.setVisible(false);
        b.setVisible(true);
        
    }//GEN-LAST:event_billBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        spe(spea);
    }//GEN-LAST:event_formWindowActivated

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
        spea="Now you are going to formulate emails";
 spe(spea);
        this.setVisible(false);
        ListItems l=new ListItems();
        l.setVisible(true);
        
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton logoutBtn1;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton stocksBtn;
    private javax.swing.JButton supplierBtn;
    // End of variables declaration//GEN-END:variables
}
