/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Date;


/**
 *
 * @author HUDA
 */
public class OrderTableEntry extends javax.swing.JFrame {
Connection con;
Statement smt;
ResultSet rs;
String id;
Email e=new Email();
    /**
     * Creates new form OrderTableEntry
     */
    public OrderTableEntry() {
        initComponents();
        getConnection();
        
        generateOid();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amtField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oidField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 140, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 120, 30);
        jPanel1.add(amtField);
        amtField.setBounds(140, 120, 190, 30);
        jPanel1.add(quantityField);
        quantityField.setBounds(140, 60, 190, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 60, 120, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter advance");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 120, 120, 30);
        jPanel1.add(oidField);
        oidField.setBounds(140, 170, 190, 30);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 220, 72, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectPackage/stationary.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        insertInTable();
        setMail();
        setSubject();
        e.getEmailType("order");
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
private void getConnection()
{
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public String getEmail()
{
    String mail="";
    try {
        smt=con.createStatement();
        String query="select email from items natural join supplier where itemid='"+id+"'";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            mail=rs.getString("email");
            
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(ListItems.class.getName()).log(Level.SEVERE, null, ex);
    }
    return mail;
}
public void setMail()
{
    String mail=getEmail();
  

    e.extractEmail(mail);
    
    
}
private int getQuantity()
{
    int x=0;
    try {
        smt=con.createStatement();
        String query="select quantity from orders where oid='"+oidField.getText()+"'";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
          x=rs.getInt("quantity");
        }
    } catch (SQLException ex) {
        Logger.getLogger(OrderTableEntry.class.getName()).log(Level.SEVERE, null, ex);
    }
    return x;
}
private void setSubject()
{
    String m=getItemName();
    Integer x=getQuantity();
        String s="Order for "+x.toString()+" packets of "+m;
        
        e.setSubject(s);
        e.setItemName(m);
        e.getQuantity(Integer.parseInt(quantityField.getText()));
        e.setAdvance(Integer.parseInt(amtField.getText()));

}
public String getItemName()
{
    String iname="";
    try {
        smt=con.createStatement();
        String query="select ItemName from items natural join supplier where itemid='"+id+"'";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            iname=rs.getString("ItemName");
            
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(ListItems.class.getName()).log(Level.SEVERE, null, ex);
    }
    return iname;
}
public String getOid()
{
     String oid1="o0";
    try {
       
        smt=con.createStatement();
        String query="select oid from orders";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            oid1=rs.getString("oid");
        }
    } catch (SQLException ex) {
        Logger.getLogger(OrderTableEntry.class.getName()).log(Level.SEVERE, null, ex);
    }
    return oid1;
}
private void generateOid()
{
    String m=getOid();
    m=m.substring(1);
    int x=Integer.parseInt(m);
    x++;
    Integer y=x;
    m="o"+y.toString();
    oidField.setText(m);
    
}
public void getItemId(String id)
{
    this.id=id;
    
}

private void insertInTable()
{
    try {
       
        
        Date d=new Date();
        java.sql.Date sql=new java.sql.Date(d.getTime());
        int amount=Integer.parseInt(amtField.getText());
        int quantity=Integer.parseInt(quantityField.getText());
        smt=con.createStatement();
    String query="insert into orders(oid,odate,quantity,amount,ItemId) values('"+oidField.getText()+"','"+sql+"',"+quantity+","+amount+",'"+id+"')";
        smt.executeUpdate(query);
    } catch (SQLException ex) {
        Logger.getLogger(OrderTableEntry.class.getName()).log(Level.SEVERE, null, ex);
    }
 
    
    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTableEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTableEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTableEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTableEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTableEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField oidField;
    private javax.swing.JTextField quantityField;
    // End of variables declaration//GEN-END:variables
}
