/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author HUDA
 */
public class Stocks extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Stocks() {
        initComponents();
        
       DefaultTableModel model=(DefaultTableModel)stockTable.getModel();
   Connection con;
   Statement smt;
   ResultSet rs;
   String stockId = null;
   String itemId = null;
   int  quantity = 0;
   try
   {
        Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
            String query="Select * from stocks";
            smt=con.createStatement();
            rs=smt.executeQuery(query);
            while(rs.next())
            {
                 stockId=rs.getString("StockId");
                 itemId=rs.getString("ItemId");
                 quantity=rs.getInt("Quantity");
                  model.addRow(new Object[]{stockId,itemId,quantity});

               
            }
              }    catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addStock = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        contactSupplier = new javax.swing.JButton();
        updateStock = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        deleteStocks1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supplier");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 110, 30);

        addStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStock.setForeground(new java.awt.Color(51, 51, 255));
        addStock.setText("Add Stocks");
        addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockActionPerformed(evt);
            }
        });
        jPanel1.add(addStock);
        addStock.setBounds(30, 210, 140, 30);

        logOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(51, 51, 255));
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut);
        logOut.setBounds(240, 260, 140, 30);

        contactSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactSupplier.setForeground(new java.awt.Color(51, 51, 255));
        contactSupplier.setText("ContactSupplier");
        contactSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(contactSupplier);
        contactSupplier.setBounds(320, 210, 140, 30);

        updateStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateStock.setForeground(new java.awt.Color(51, 51, 255));
        updateStock.setText("Update Stocks");
        updateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockActionPerformed(evt);
            }
        });
        jPanel1.add(updateStock);
        updateStock.setBounds(80, 260, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ItemId");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 140, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("StockId");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 140, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 110, 140, 40);
        jPanel1.add(itemField);
        itemField.setBounds(130, 80, 170, 30);
        jPanel1.add(quantityField);
        quantityField.setBounds(130, 110, 170, 30);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idField);
        idField.setBounds(130, 50, 170, 30);

        deleteStocks1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteStocks1.setForeground(new java.awt.Color(51, 51, 255));
        deleteStocks1.setText("Delete Stocks");
        deleteStocks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStocks1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteStocks1);
        deleteStocks1.setBounds(170, 210, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Desktop\\complete web development\\pictures\\stationary.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 330);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Supplier Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 140, 140, 40);

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StockId", "ItemId", "Quantity"
            }
        ));
        stockTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stockTableFocusGained(evt);
            }
        });
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stockTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed
        // TODO add your handling code here:
       
     
         Connection con;
       Statement sm;
       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
            sm=con.createStatement();
            String query="insert into stocks(StockId,ItemId,Quantity) values('"+idField.getText()+"','"+itemField.getText()+"',"+quantityField.getText()+")";
	 
	 
            sm.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null,"InsertedSuccesfully");
       
            addRowToTable();
              
            
        }
        catch(ClassNotFoundException | SQLException cnfe)
        {
             JOptionPane.showMessageDialog(null,cnfe);
        }

    }//GEN-LAST:event_addStockActionPerformed
public void addRowToTable()
{
    DefaultTableModel model=(DefaultTableModel)stockTable.getModel();
   Connection con;
   Statement smt;
   ResultSet rs;
   String stockId = null;
   String itemId = null;
   int  quantity = 0;
   try
   {
        Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
            String query="Select * from stocks";
            smt=con.createStatement();
            rs=smt.executeQuery(query);
            while(rs.next())
            {
                 stockId=rs.getString("StockId");
                 itemId=rs.getString("ItemId");
                 quantity=rs.getInt("Quantity");
               
            }
            model.addRow(new Object[]{stockId,itemId,quantity});
   }    catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        MainPage a=new MainPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutActionPerformed

    private void contactSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactSupplierActionPerformed
        // TODO add your handling code here:
                
        DefaultTableModel model=(DefaultTableModel)stockTable.getModel();
        Connection con;
        Statement smt;
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
             smt=con.createStatement();
            String query="delete from stocks where StockId='"+idField.getText()+"'";
           
            smt.executeUpdate(query);
           int row=stockTable.getSelectedRow();
           model.removeRow(row);
           idField.setText("");
        itemField.setText("");
        quantityField.setText("");
           
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
                    } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
                    }

    }//GEN-LAST:event_contactSupplierActionPerformed

    private void updateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockActionPerformed
        // TODO add your handling code here:
        Connection con;
        Statement smt;
        
   int  quantity = Integer.parseInt(quantityField.getText());
   try
   {
   Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
             smt=con.createStatement();
   String query="update stocks set Quantity="+quantity+" where StockId='"+idField.getText()+"'";
   smt.executeUpdate(query);
     JOptionPane.showMessageDialog(null,"UpdateSucessfully");
     updateTable();
     
   }    catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_updateStockActionPerformed
public void updateTable()
{
   
    int i=stockTable.getSelectedRow();
    stockTable.getModel().setValueAt(quantityField.getText(),i,2);
}
    
    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void stockTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stockTableFocusGained
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_stockTableFocusGained

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        // TODO add your handling code here:
        int index=stockTable.getSelectedRow();
        String id= stockTable.getModel().getValueAt(index,0).toString();
        String itemId=stockTable.getModel().getValueAt(index,1).toString();
        String quantity=stockTable.getModel().getValueAt(index,2).toString();
        idField.setText(id);
        itemField.setText(itemId);
        quantityField.setText(quantity);
        int quan=Integer.parseInt(quantity);
        if(quan<5)
        {
            JOptionPane.showMessageDialog(null,"Stock for item="+itemId+"is declining contact supplier");
        }

    }//GEN-LAST:event_stockTableMouseClicked

    private void deleteStocks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStocks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteStocks1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStock;
    private javax.swing.JButton contactSupplier;
    private javax.swing.JButton deleteStocks1;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField itemField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTable stockTable;
    private javax.swing.JButton updateStock;
    // End of variables declaration//GEN-END:variables
}
