/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUDA
 */
public class Supplier extends javax.swing.JFrame {
Connection con;
   Statement smt;
   String sId;
   String str;
     ResultSet rs;
    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        this.getConnection();
     this.addInfoToTable();

    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addSupplier = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        deleteSupplier = new javax.swing.JButton();
        updateSupplier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        adressField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supplier");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 110, 30);

        addSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSupplier.setForeground(new java.awt.Color(51, 51, 255));
        addSupplier.setText("Add Supplier");
        addSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(addSupplier);
        addSupplier.setBounds(30, 210, 140, 30);

        logOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOut.setForeground(new java.awt.Color(51, 51, 255));
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut);
        logOut.setBounds(190, 260, 140, 30);

        deleteSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSupplier.setForeground(new java.awt.Color(51, 51, 255));
        deleteSupplier.setText("Delete Supplier");
        deleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(deleteSupplier);
        deleteSupplier.setBounds(190, 210, 140, 30);

        updateSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateSupplier.setForeground(new java.awt.Color(51, 51, 255));
        updateSupplier.setText("Update Supplier");
        updateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(updateSupplier);
        updateSupplier.setBounds(30, 260, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 140, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SupplierAdress");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 110, 140, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SupplierName");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 140, 40);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField);
        nameField.setBounds(130, 80, 170, 30);
        jPanel1.add(adressField);
        adressField.setBounds(130, 110, 170, 30);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idField);
        idField.setBounds(130, 50, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SupplierId");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 50, 140, 40);
        jPanel1.add(emailField);
        emailField.setBounds(130, 140, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HUDA\\Desktop\\complete web development\\pictures\\stationary.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 330);

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SupplierId", "SupplierName", "SupplierAdress", "Phoneno"
            }
        ));
        supplierTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                supplierTableFocusGained(evt);
            }
        });
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void getConnection()
{
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
    }
}
private void addInfoToTable()
{
      DefaultTableModel model=(DefaultTableModel)supplierTable.getModel();
   
 
  String supplierId ="s0";
   String supplierName = null;
              String supplierAdress= null;
                 String stockId = null;
   String email;
   try
   {
        Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stationaryandgiftshop?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
            String query="Select * from supplier";
            smt=con.createStatement();
            rs=smt.executeQuery(query);
            while(rs.next())
            {
           

                 supplierId=rs.getString("SupplierId");
                 supplierName=rs.getString("SupplierName");
                 supplierAdress=rs.getString("SupplierAddress");
                  
                   email=rs.getString("email");
                 
               
            
            model.addRow(new Object[]{supplierId,supplierName,supplierAdress,email});
               
            }
            setSupplierId(supplierId);
            
            generateId();
            
            this.setSupplierId(supplierId);
              }    catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
}
private void setSupplierId(String supplierId)
{
    
   sId =supplierId;
}
private String getSupplierId()
{
    return sId;
}
private void generateId()
{
    str=getSupplierId();
    int x=Integer.parseInt(str.substring(1));
    x++;
    Integer y=x;
    str="s"+y.toString();
    idField.setText(str);
}

    private void addSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierActionPerformed
        // TODO add your handling code here:
       
     
       
       
        try {
           
            smt=con.createStatement();
            String query="insert into supplier(SupplierId,SupplierName,SupplierAddress,email) values('"+idField.getText()+"','"+nameField.getText()+"','"+adressField.getText()+"','"+emailField.getText()+"')";
	 
	 
            smt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null,"InsertedSuccesfully");
       
            addRowToTable();
              
            
        }
        catch(SQLException cnfe)
        {
             JOptionPane.showMessageDialog(null,cnfe);
        }
    }//GEN-LAST:event_addSupplierActionPerformed
public void addRowToTable()
{
    DefaultTableModel model=(DefaultTableModel)supplierTable.getModel();
   
     
            model.addRow(new Object[]{idField.getText(),nameField.getText(),adressField.getText(),emailField.getText()});
      makeEmpty();
          getIde();
}
    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        MainPage a=new MainPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutActionPerformed

    private void deleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierActionPerformed
        // TODO add your handling code here:
                
        DefaultTableModel model=(DefaultTableModel)supplierTable.getModel();
       
        
        try
        {
            
             smt=con.createStatement();
            String query="delete from supplier where SupplierId='"+idField.getText()+"'";
           
            smt.executeUpdate(query);
           int row=supplierTable.getSelectedRow();
           model.removeRow(row);
          makeEmpty();
          getIde();
        
        
           
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
                    } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
                    }

    }//GEN-LAST:event_deleteSupplierActionPerformed
private void makeEmpty()
{
    idField.setText("");
    nameField.setText("");
    adressField.setText("");
    
    emailField.setText(" ");
    
}
private void getIde()
{
     String id="s0";
    try {
        smt=con.createStatement();
        String query="select * from items";
        rs=smt.executeQuery(query);
        while(rs.next())
        {
            id=rs.getString("SupplierId");
            
        }
        this.setSupplierId(id);
        
    } catch (SQLException ex) {
        Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        // TODO add your handling code here:
      
        
   
   try
   {
   
             smt=con.createStatement();
   String query="update supplier set SupplierName='"+nameField.getText()+"',SupplierAddress='"+adressField.getText()+"',email='"+emailField.getText()+"' where SupplierId='"+idField.getText()+"'";
   smt.executeUpdate(query);
     JOptionPane.showMessageDialog(null,"UpdateSucessfully");
     updateTable();
     
   }    catch (SQLException ex) {
            Logger.getLogger(Stocks.class.getName()).log(Level.SEVERE, null, ex);
        
        } 
        
                                              
    }//GEN-LAST:event_updateSupplierActionPerformed
public void updateTable()
{
   
    int i=supplierTable.getSelectedRow();
    supplierTable.getModel().setValueAt(nameField.getText(),i,1);
      supplierTable.getModel().setValueAt(adressField.getText(),i,2);
        supplierTable.getModel().setValueAt(emailField.getText(),i,3);
           makeEmpty();
          getIde();
}
    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void supplierTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_supplierTableFocusGained
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_supplierTableFocusGained

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        // TODO add your handling code here:
        int index=supplierTable.getSelectedRow();
        String id= supplierTable.getModel().getValueAt(index,0).toString();
        String name=supplierTable.getModel().getValueAt(index,1).toString();
        String adress=supplierTable.getModel().getValueAt(index,2).toString();
       
          String number=supplierTable.getModel().getValueAt(index,3).toString();
        idField.setText(id);
        nameField.setText(name);
        adressField.setText(adress);
         
          emailField.setText(number);

    }//GEN-LAST:event_supplierTableMouseClicked

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplier;
    private javax.swing.JTextField adressField;
    private javax.swing.JButton deleteSupplier;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable supplierTable;
    private javax.swing.JButton updateSupplier;
    // End of variables declaration//GEN-END:variables
}
